Support to CPF and CNPJ
OpenCraft/GeneralFormatter pull request #2
Opened 2017-06-24 19:41 UTC by CristianDRM

- Refactory to conform with SOLID Pattern
 - Add support to CPF and CPNJ mask

2017-06-25 00:33 UTC, Morbix commented on GeneralFormatter.podspec
> +  s.version          = '2'
Prefer `2.0.0`

2017-06-25 00:34 UTC, Morbix commented on Example/Pods/Target Support Files/GeneralFormatter/Info.plist
> +  <string>1.1.1</string>
Why it is 1.1.1?

2017-06-25 00:34 UTC, Morbix commented on GeneralFormatter/Classes/CNPJFormatter.swift
> +//
Remove all headers

2017-06-25 00:34 UTC, Morbix commented on Example/GeneralFormatter/Base.lproj/Main.storyboard
>                          <rect key="frame" x="0.0" y="0.0" width="375" height="667"/>
Update README

2017-06-25 00:35 UTC, Morbix requested changes
Fix comments

2017-06-25 00:35 UTC, Morbix commented
By the way, very nice Refactor.

2017-06-25 00:37 UTC, Morbix commented
@UrielBattanoli I'll need release a new version of the pod, could you add me as a contributor, please?

2017-06-25 18:46 UTC, CristianDRM commented
Reviewed

2017-06-26 10:30 UTC, Morbix commented on GeneralFormatter/Classes/GeneralFormatter.swift
> +    case custom(formatter: Formatter)
You did again!!! >/

2017-06-26 10:30 UTC, Morbix approved these changes

2017-06-26 10:54 UTC, merged